Mini-Blog-Engine/Mini-Blog-Engine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Mini_Blog_Engine.Models;

namespace Mini_Blog_Engine.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
            var con = SQL_String.GetConnection();
            SqlCommand cmd = new SqlCommand();
            cmd.CommandText = "SELECT [Title], [Description], [content], [Id] FROM [dbo].[Post] WHERE DeletedOn IS Null";
            cmd.Connection = con;
			con.Open();

			var reader = cmd.ExecuteReader();
			var list = new List<Post>();
			if (reader.HasRows)
			{
				while (reader.Read())
				{
					list.Add(new Post()
					{
						Title = reader.GetString(0),
						Description = reader.GetString(1),
						Content = reader.GetString(2),
						Id = reader.GetInt32(3)
					});
				}
			}
			else
			{
				ViewBag.Message = "Keine Einträge gefunden.";
			}

			con.Close();
			return View(list);
		}
	}
}


/*
 * Frage 1:  Warum haben Sie sich für gerade für den Hash Algorithmus (Usernamen & Passwort) entschieden?
 * 
 * Wir haben den sha256 Algorithmus verwendet, wenn wir mehr Zeit für das Projekt gehabt hätten.
 * Wir hätten uns für den SHA-3 Algorithmus entschieden, da dies der aktuellste und somit unserer Meinung nach der sicherste Algorithmus ist.
 *
 * 
 * 
 * Frage 2: In der User-Login-Tabelle ist noch ein Feld für die IP-Adresse Reserviert. Welche Attacke lässt sich dadurch verhindern?
 * 
 * Über die Session-ID eines Benutzers einloggen
 * 
 * 
 * 
 * Frage 3:  Erklären Sie, wie diese Attacke genau funktioniert und inwiefern die Gegenmassnahmen die Attacke vereitelt?
 * 
 * Der Hacker "klaut" die Session-ID eines bereits vorhandenen Benutzers. Die Gegenmassnahme dafür ist das Abfragen der IP-Adresse. Man kann somit überprüfen, 
 * ob es sich bei der Anmeldung um eine fremde IP-Adresse und somit auch um einen potenziellen Hacker handelt.
 *
 */

Mini-Blog-Engine/Mini-Blog-Engine/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mini_Blog_Engine.Models;

namespace Mini_Blog_Engine.Controllers
{
    public class PostController : Controller
    {
		public ActionResult Index(int id)
        {
            var con = SQL_String.GetConnection();

            SqlCommand cmd = new SqlCommand
			{
				CommandText = "SELECT Commet FROM [dbo].[Comment] WHERE PostId = " + id,
				Connection = con
			};

			con.Open();

			var reader = cmd.ExecuteReader();

			var list = new List<string>();
			if (reader.HasRows)
			{
				while (reader.Read())
				{
					list.Add(reader.GetString(0));
				}
			}

			SqlCommand cmdPost = new SqlCommand
			{
				CommandText = "SELECT [Title], [Description], [content] FROM [dbo].[Post] WHERE Id = " + id,
				Connection = con
			};
			reader = cmdPost.ExecuteReader();

			var post = new Post();
			while (reader.Read())
			{
				post = new Post()
				{
					Title = reader.GetString(0),
					Description = reader.GetString(1),
					Content = reader.GetString(2),
					Id = id
				};
			}
			con.Close();

			post.Comments = list;
			return View(post);
		}

		[HttpPost]
		public ActionResult AddComment()
		{
			var comment = Request["comment"];
		    var id = Request["id"];

            if (!comment.All(char.IsLetterOrDigit))
		        return RedirectToAction("Index", "Home");

			if (!string.IsNullOrEmpty(comment) && comment.Length < 200)
			{
			    var con = SQL_String.GetConnection();
				SqlCommand cmd = new SqlCommand
				{
					CommandText = "INSERT INTO [dbo].[Comment] (commet, PostId) VALUES('" + comment + "', " + id + ")",
					Connection = con
				};
				con.Open();
				cmd.ExecuteReader();
				ViewBag.Message = "";
				con.Close();
			}
			else
			{
				ViewBag.Message = "Text ist zu lang oder ist leer!";
			}

		    return View();
		}
	}
}

Mini-Blog-Engine/Mini-Blog-Engine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Mini-Blog-Engine/Mini-Blog-Engine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Mini-Blog-Engine/Mini-Blog-Engine/Views/Home/Index.cshtml
@model List<Mini_Blog_Engine.Models.Post>
@{
    ViewBag.Title = "Mini-Blog-Engine";
}

<div class="jumbotron">
	<h1>Mini-Blog-Engine</h1>
	<p class="lead">Module 183 Project</p>
</div>

<div class="row" style="margin-top:80px;">

	<div class="col-lg-8 col-lg-offset-2">
		<table class="table table-hover">
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>Content</th>
				<th>Detailansicht</th>
			</tr>
			@foreach(var post in Model)
			{
				<tr>
					<td>@post.Title</td>  
					<td>@post.Description</td>  
					<td>@post.Content</td> 
					<td>@Html.ActionLink("Details", "Index", "Post", new { id = post.Id }, null)</td>
				</tr>
			}
		</table>
	</div>
</div>